"""Dev-only: render sample plan PDFs without a database or Supabase.

Builds a realistic Arabic plan (long meal names, missing photos, empty
sections, a day with a single meal) and renders it through the real
pdf_renderer, so every layout can be eyeballed before shipping.

    # every layout, default palette
    python tools/preview_pdf.py

    # one design in one palette
    python tools/preview_pdf.py --layout editorial --theme sand

    # the whole matrix
    python tools/preview_pdf.py --all-themes

On macOS WeasyPrint needs Homebrew's pango/cairo on the dylib path:

    DYLD_FALLBACK_LIBRARY_PATH=/opt/homebrew/lib .venv/bin/python tools/preview_pdf.py
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from app.layouts import LAYOUTS  # noqa: E402
from app.pdf_renderer import render_plan_pdf  # noqa: E402
from app.themes import THEMES  # noqa: E402

OUT_DIR = Path("/tmp/nutriflow-previews")
REPO_ROOT = ROOT.parent


def _photo(name: str) -> str | None:
    """Sample meal photos are generated by tools/make_sample_photos.py into
    /tmp; a missing file just renders the card without an image, which is
    itself a case worth previewing."""
    path = OUT_DIR / "photos" / f"{name}.png"
    return path.as_uri() if path.exists() else None


def _logo() -> str | None:
    logo = REPO_ROOT / "logo_no_background.jpeg"
    return logo.as_uri() if logo.exists() else None


def _ing(item: str, amount=None, unit: str = "") -> dict:
    return {"item": item, "amount": amount, "unit": unit}


SAMPLE_MEALS = [
    {
        "meal_type": "breakfast",
        "custom_name": None,
        "custom_ingredients": None,
        "recipe": {
            "name": "أومليت السبانخ بالجبن القريش",
            "image_url": _photo("breakfast"),
            "tip": "تكفي ملعقة صغيرة من زيت الزيتون مع مقلاة غير لاصقة.",
            "ingredients": [
                _ing("بيض", 2, "حبة"),
                _ing("سبانخ طازجة", 50, "غرام"),
                _ing("جبن قريش", 30, "غرام"),
                _ing("زيت زيتون", 1, "ملعقة صغيرة"),
            ],
        },
    },
    {
        "meal_type": "snack",
        "custom_name": "تفاحة مع ملعقة زبدة لوز",
        "custom_ingredients": [_ing("تفاح", 1, "حبة"), _ing("زبدة لوز", 1, "ملعقة")],
        "recipe": None,
    },
    {
        "meal_type": "lunch",
        "custom_name": None,
        "custom_ingredients": None,
        "recipe": {
            "name": "صدر دجاج مشوي مع أرز بسمتي وخضار سوتيه",
            "image_url": _photo("lunch"),
            "tip": "نقع الأرز ٢٠ دقيقة قبل الطهي يقلّل وقت الطهي والسعرات الممتصة.",
            "ingredients": [
                _ing("صدر دجاج", 150, "غرام"),
                _ing("أرز بسمتي مطبوخ", 100, "غرام"),
                _ing("كوسا وجزر", 100, "غرام"),
                _ing("ليمون", 0.5, "حبة"),
            ],
        },
    },
    {
        "meal_type": "salad",
        "custom_name": None,
        "custom_ingredients": None,
        "recipe": {
            "name": "سلطة يونانية",
            "image_url": None,
            "tip": None,
            "ingredients": [
                _ing("خيار", 1, "حبة"),
                _ing("طماطم", 1, "حبة"),
                _ing("جبن فيتا", 20, "غرام"),
                _ing("زيتون أسود", 5, "حبات"),
            ],
        },
    },
    {
        "meal_type": "dinner",
        "custom_name": None,
        "custom_ingredients": None,
        "recipe": {
            "name": "شوربة عدس مع توست أسمر",
            "image_url": _photo("dinner"),
            "tip": "يُفضّل تناولها قبل النوم بساعتين على الأقل.",
            "ingredients": [
                _ing("عدس أحمر", 60, "غرام"),
                _ing("توست أسمر", 1, "شريحة"),
                _ing("كمون وليمون", None, ""),
            ],
        },
    },
]


def build_context(layout_id: str, theme_id: str) -> dict:
    days = [
        {
            "day_number": 1,
            "motivational_text": "البداية دائمًا أصعب خطوة — وقد تمّت بالفعل.",
            "meals": SAMPLE_MEALS,
        },
        {
            "day_number": 2,
            "motivational_text": "الاستمرارية أهم من الكمال.",
            "meals": SAMPLE_MEALS[:4],
        },
        # A near-empty day: exercises the single-card and no-banner paths.
        {
            "day_number": 3,
            "motivational_text": None,
            "meals": SAMPLE_MEALS[:1],
        },
    ]

    return {
        "plan": {
            "patient_name": "نور عبدالله الحربي",
            "dietitian_name": "أ. سارة العتيبي",
            "duration_days": 7,
            "fasting_hours": 16,
            "fasting_notes": "يُسمح خلال فترة الصيام بالماء والقهوة والشاي بدون سكر أو حليب.",
            "general_notes": (
                "شرب ٢–٢.٥ لتر ماء يوميًا، والمشي ٣٠ دقيقة على الأقل ٥ أيام في الأسبوع. "
                "يُقاس الوزن مرة واحدة أسبوعيًا صباحًا على معدة فارغة، وتذبذب الوزن "
                "اليومي أمر طبيعي تمامًا."
            ),
            "theme": theme_id,
            "pdf_layout": layout_id,
        },
        "dietitian": {"name": "عيادة سارة العتيبي للتغذية", "logo_url": _logo()},
        "days": days,
        "drinks": [
            {
                "name": "مشروب الزنجبيل والليمون",
                "timing": "قبل الفطور",
                "ingredients": [
                    _ing("زنجبيل مبشور", 1, "ملعقة صغيرة"),
                    _ing("ليمون", 0.5, "حبة"),
                    _ing("ماء دافئ", 250, "مل"),
                ],
            },
            {
                "name": "شاي أخضر بالنعناع",
                "timing": "بعد الغداء",
                "ingredients": [_ing("شاي أخضر", 1, "كيس"), _ing("نعناع طازج", 4, "أوراق")],
            },
        ],
        "supplements": [
            {
                "dose": "1000 وحدة",
                "timing": "بعد الفطور",
                "notes": "مع وجبة تحتوي دهون",
                "supplement": {"name": "فيتامين د"},
            },
            {
                "dose": None,
                "timing": None,
                "notes": None,
                "supplement": {
                    "name": "أوميغا 3",
                    "default_dose": "1000 ملغ",
                    "default_timing": "بعد الغداء",
                    "default_notes": "يُحفظ في الثلاجة",
                },
            },
            {
                "dose": "200 ملغ",
                "timing": "قبل النوم",
                "notes": "يساعد على الاسترخاء",
                "supplement": {"name": "مغنيسيوم"},
            },
        ],
        "allowed_foods": [
            {"category": "بروتينات", "item": "دجاج منزوع الجلد"},
            {"category": "بروتينات", "item": "سمك"},
            {"category": "بروتينات", "item": "بيض"},
            {"category": "بروتينات", "item": "لحم بقري قليل الدهن"},
            {"category": "بروتينات", "item": "تونة بالماء"},
            {"category": "نشويات", "item": "أرز بسمتي"},
            {"category": "نشويات", "item": "شوفان"},
            {"category": "نشويات", "item": "بطاطا حلوة"},
            {"category": "نشويات", "item": "خبز أسمر"},
            {"category": "خضار", "item": "خيار"},
            {"category": "خضار", "item": "بروكلي"},
            {"category": "خضار", "item": "سبانخ"},
            {"category": "خضار", "item": "فلفل ألوان"},
            {"category": "دهون صحية", "item": "أفوكادو"},
            {"category": "دهون صحية", "item": "زيت زيتون"},
            {"category": "دهون صحية", "item": "لوز نيء"},
        ],
        "forbidden_foods": [
            {"category": "سكريات", "item": "مشروبات غازية"},
            {"category": "سكريات", "item": "حلويات جاهزة"},
            {"category": "سكريات", "item": "عصائر معلّبة"},
            {"category": "مقليات", "item": "بطاطس مقلية"},
            {"category": "مقليات", "item": "وجبات سريعة"},
            {"category": "أخرى", "item": "صلصات جاهزة"},
            {"category": "أخرى", "item": "مايونيز"},
        ],
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--layout", help="render a single layout id")
    parser.add_argument("--theme", default="emerald")
    parser.add_argument("--all-themes", action="store_true")
    args = parser.parse_args()

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    layout_ids = [args.layout] if args.layout else list(LAYOUTS)
    theme_ids = list(THEMES) if args.all_themes else [args.theme]

    for layout_id in layout_ids:
        for theme_id in theme_ids:
            name = f"{layout_id}-{theme_id}.pdf"
            pdf = render_plan_pdf(build_context(layout_id, theme_id))
            (OUT_DIR / name).write_bytes(pdf)
            print(f"{OUT_DIR / name}  ({len(pdf) // 1024} KB)")


if __name__ == "__main__":
    main()
